#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
export LC_ALL=C

# EXCLUDE: Skills that must not receive the generated block.
EXCLUDE=(
  "dev-utilities/writing-skills" # Authors other skills, so an embedded block would propagate; it carries an optional authored principle instead.
  "codebase-automations/dependabot-fix" # Runs as an isolated child of dependabot-fix-all, which owns the single feedback loop for the batch session.
  "dev-utilities/explain-code-walkthrough" # Mainly-text support skill whose output can be judged directly without automatic upstream reporting.
  "dev-utilities/standardize-agent-instructions" # Support skill focused mainly on instruction-file layout; keep the baseline off lightweight maintenance runs.
  "workflow-automations/verify-streamlit-app" # Support verifier for create-streamlit-app; the creating parent owns one feedback loop for the paired session.
  "workflow-automations/new-project" # RPI stages must stop at their explicit user handover rather than continue into automatic reporting.
  "workflow-automations/rpi-research" # RPI stages must stop at their explicit user handover rather than continue into automatic reporting.
  "workflow-automations/rpi-adrs" # RPI stages must stop at their explicit user handover rather than continue into automatic reporting.
  "workflow-automations/rpi-plan" # RPI stages must stop at their explicit user handover rather than continue into automatic reporting.
  "workflow-automations/rpi-implement" # RPI stages must stop at their explicit user handover rather than continue into automatic reporting.
)

START='<!-- baseline:start - generated by scripts/sync-skill-baseline-block.sh, do not edit by hand -->'
END='<!-- baseline:end -->'
TEMPLATE='scripts/skill-baseline-block.md'
EXPECTED_SKILL_COUNT=16
MODE='apply'

if [ "$#" -gt 1 ]; then
  echo "Usage: $0 [apply|--check]" >&2
  exit 2
fi
if [ "$#" -eq 1 ]; then
  case "$1" in
    apply|--check) MODE="$1" ;;
    *)
      echo "Usage: $0 [apply|--check]" >&2
      exit 2
      ;;
  esac
fi

start_count=$(grep -Fxc "$START" "$TEMPLATE" || true)
end_count=$(grep -Fxc "$END" "$TEMPLATE" || true)
if [ "$start_count" -ne 1 ] || [ "$end_count" -ne 1 ] ||
   [ "$(head -n 1 "$TEMPLATE")" != "$START" ] || [ "$(tail -n 1 "$TEMPLATE")" != "$END" ]; then
  echo "ERROR: $TEMPLATE must contain exactly one start marker and one end marker" >&2
  exit 1
fi

mkdir -p "$PWD/tmp"
tmp_dir=$(mktemp -d "$PWD/tmp/skill-baseline.XXXXXX")
trap 'rm -rf "$tmp_dir"' EXIT

is_excluded() {
  local candidate=$1
  local excluded
  for excluded in "${EXCLUDE[@]}"; do
    if [ "$candidate" = "$excluded" ]; then
      return 0
    fi
  done
  return 1
}

strip_block() {
  local source=$1
  local destination=$2
  awk -v start="$START" -v end="$END" '
    skipping && $0 == end { skipping = 0; gap = 1; next }
    skipping { next }
    $0 == start {
      if (held && line != "") print line
      held = 0
      skipping = 1
      next
    }
    gap && $0 == "" { next }
    gap {
      print ""
      gap = 0
    }
    {
      if (held) print line
      line = $0
      held = 1
    }
    END {
      if (held) print line
    }
  ' "$source" > "$destination"
}

insert_block() {
  local source=$1
  local destination=$2
  local plugin=$3

  if [ "$(head -n 1 "$source")" = '---' ]; then
    if ! awk -v template="$TEMPLATE" -v plugin="$plugin" '
      function print_block( line) {
        while ((getline line < template) > 0) {
          gsub(/<plugin>/, plugin, line)
          print line
        }
        close(template)
      }
      NR > 1 && !inserted && $0 == "---" {
        print; print ""; print_block(); print ""; inserted = 1; after = 1; next
      }
      after && $0 == "" { next }
      after { after = 0 }
      { print }
      END {
        if (!inserted) exit 3
      }
    ' "$source" > "$destination"; then
      echo "ERROR: $source has no closing frontmatter marker" >&2
      return 1
    fi
  else
    awk -v template="$TEMPLATE" -v plugin="$plugin" '
      function print_block( line) {
        while ((getline line < template) > 0) {
          gsub(/<plugin>/, plugin, line)
          print line
        }
        close(template)
      }
      BEGIN { print_block(); print ""; leading = 1 }
      leading && $0 == "" { next }
      { leading = 0; print }
    ' "$source" > "$destination"
  fi
}

skills=(plugins/*/skills/*/SKILL.md)
if [ "${#skills[@]}" -ne "$EXPECTED_SKILL_COUNT" ]; then
  echo "ERROR: expected $EXPECTED_SKILL_COUNT SKILL.md files, found ${#skills[@]}; update EXPECTED_SKILL_COUNT if the catalogue grew" >&2
  exit 1
fi

status=0
processed=0
for file in "${skills[@]}"; do
  processed=$((processed + 1))
  plugin=${file#plugins/}
  plugin=${plugin%%/*}
  skill=${file#plugins/$plugin/skills/}
  skill=${skill%/SKILL.md}
  key="$plugin/$skill"
  destination="$tmp_dir/$file"
  mkdir -p "$(dirname "$destination")"

  file_start_count=$(grep -Fxc "$START" "$file" || true)
  file_end_count=$(grep -Fxc "$END" "$file" || true)
  if { [ "$file_start_count" -ne 0 ] && [ "$file_start_count" -ne 1 ]; } ||
     { [ "$file_end_count" -ne 0 ] && [ "$file_end_count" -ne 1 ]; } ||
     [ "$file_start_count" -ne "$file_end_count" ]; then
    echo "ERROR: $file has unmatched or duplicate baseline markers" >&2
    exit 1
  fi
  if [ "$file_start_count" -eq 1 ]; then
    start_line=$(grep -Fn "$START" "$file" | cut -d: -f1)
    end_line=$(grep -Fn "$END" "$file" | cut -d: -f1)
    if [ "$start_line" -ge "$end_line" ]; then
      echo "ERROR: $file has baseline markers in the wrong order" >&2
      exit 1
    fi
  fi

  if is_excluded "$key"; then
    if [ "$file_start_count" -eq 1 ]; then
      strip_block "$file" "$destination"
    else
      cp "$file" "$destination"
    fi
  else
    candidate_source=$file
    if [ "$file_start_count" -eq 1 ]; then
      candidate_source="$destination.stripped"
      strip_block "$file" "$candidate_source"
    fi
    insert_block "$candidate_source" "$destination" "$plugin"
  fi

  if ! cmp -s "$file" "$destination"; then
    if [ "$MODE" = '--check' ]; then
      diff -u "$file" "$destination" || true
      status=1
    else
      cp "$destination" "$file"
      echo "UPDATED: $file"
    fi
  fi
done

if [ "$processed" -ne "$EXPECTED_SKILL_COUNT" ]; then
  echo "ERROR: processed $processed SKILL.md files, expected $EXPECTED_SKILL_COUNT" >&2
  exit 1
fi
if [ "$status" -ne 0 ]; then
  exit "$status"
fi
echo "OK"
